### ISSUE TITLE
Error when placing order

### ISSUE THREAD

**Issue by takshingc** [blockworks-foundation/mango-explorer-v4#1]
I try to follow the example to place an order: https://github.com/blockworks-foundation/mango-explorer-v4/blob/master/examples/place_order.py

But no luck, keep returning:

```solana.rpc.core.RPCException: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 0: custom program error: 0x9c5", data: RpcSimulateTransactionResult { err: Some(Tagged(InstructionError(TransactionErrorInstructionError((0, Tagged(Custom(InstructionErrorCustom(2501)))))))), logs: Some(["Program 4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg invoke [1]", "Program log: Instruction: Serum3PlaceOrder", "Program log: AnchorError thrown in programs/mango-v4/src/health/account_retriever.rs:85. Error Code: RequireEqViolated. Error Number: 2501. Error Message: A require_eq expression was violated; loading bank with health account index 0, token index 4, passed account J6MsZiJUU6bjKSCkbfQsiHkd8gvJoddG2hsdSFsZQEZV; pre-withdraw init health.", "Program log: Left: 0", "Program log: Right: 4", "Program 4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg consumed 38986 of 200000 compute units", "Program 4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg failed: custom program error: 0x9c5"]), accounts: None, units_consumed: Some(0), return_data: None } }```

Even if I bypass the preflight check, the transaction would still fail.

I tried to cross check a successful order placed using the web gui on solscan, some contract addresses seem different. Maybe the issue is related to the `id.json` data?

**Comment by waterquarks** [comment]
Hi, thanks for reaching out - I've added a [new section](https://github.com/blockworks-foundation/mango-explorer-v4#running-the-examples) to the readme elaborating on how to run the example code, including order placement & cancellation - please note that it's necessary to update mango-explorer-v4 to >= 0.7.3 beforehand; the following snippet
```bash
python -m mango_explorer_v4.examples.place_order \
    --keypair [KEYPAIR] \
    --mango-account [MANGO_ACCOUNT] \
    --symbol SOL-PERP \
    --side bids \
    --price 1 \
    --size 0.1
```
yields a [transaction](https://explorer.solana.com/tx/4BULDkrVpVabURb2tbt5WKG2AHxxFHEm1M9GnS3okZXPTNSXEHRxj1tZLJcTjo498RQbqq8vsB2kQugS28D4uGHw), so seems like it'd be a matter of adjusting the parameters. Let me know whether you were able to place an order now?

**Comment by takshingc** [comment]
Hi, thanks for you reply!

I updated the mango-explorer-v4 to 0.7.4, but still does not work.

I tried to mimic the order created on mango gui, I gave the same order params, the transaction still did not go throught...

Mango gui (successful): https://explorer.solana.com/tx/5RBtthPgPZorheMXbj3Q7jen78MbJdXdPgEEda9RXRg7XgHwQCV2Kbrg9dMeZtNffSY1qL2rCDBx3xQdhfLJ7zRq

Python (failed): https://explorer.solana.com/tx/J59Wz2wb86w88dgG77jdcr3BytVGArV8RVgBuN5A6dDfVbG7q1Cr3yY5W3pv7Nh2fQwGVnFTxDgU4uWe1vWWzTn

My mango account id is: CXK4yA2MzvBnj4XnXtS34RcCAr6mN9xxvhJyyRzyYW2y

**Comment by waterquarks** [comment]
Hi, thanks for sharing the transaction logs - will review and revert shortly; could you try placing an order on a perpetual market as well to see whether it'd produce a similar error? I'll be patching this on spot markets in the meantime.

**Comment by waterquarks** [comment]
> some contract addresses seem different

Indeed seems like it was an issue with the ordering of some addresses - just released a [new version](https://github.com/blockworks-foundation/mango-explorer-v4/commit/81786b452da4ccf26d0c0641f50de757dc095639) of the SDK accounting for this, could you please update to 0.7.5 and try placing an order again?

**Comment by waterquarks** [comment]
User reports in DMs that the patch submitted to 0.7.5 resolved the issue - he can place orders now.
